version: '3.7'

services:
  database:
    image: mysql:latest
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=realestate
      - MYSQL_PASSWORD=realestate
      - MYSQL_DATABASE=realestate
    networks:
      - database_net
    ports:
      - 3306:3306
    volumes:
      - database_data:/var/lib/mysql
      - ./BDD/init-db:/docker-entrypoint-initdb.d
    command: --default_authentication_plugin=mysql_native_password
  adminer:
    image: dehy/adminer
    networks:
      - database_net
    ports:
      - 8080:80
  flask:
    build:
      context: ./
      dockerfile: ./prediction_container/Dockerfile
    container_name: flask
    image: flask-py
    restart: always
    ports:
      - 8081:5000

networks:
  database_net:
    driver: bridge

volumes:
  database_data:
